-- User to user payment request queue
CREATE TABLE IF NOT EXISTS public.user_transfer_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  requester_guest_id TEXT NOT NULL,
  requester_verified_count INTEGER NOT NULL DEFAULT 0,
  requester_payment_number TEXT NOT NULL,
  requester_payment_method TEXT,
  target_guest_id TEXT NOT NULL,
  target_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  submitted_batch_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.user_request_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  target_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  target_guest_id TEXT NOT NULL,
  target_display_name TEXT,
  target_verified_count INTEGER NOT NULL DEFAULT 0,
  submitted_to_admin_by TEXT NOT NULL DEFAULT 'Unknown',
  request_count INTEGER NOT NULL DEFAULT 0,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_schema = 'public'
      AND table_name = 'user_transfer_requests'
      AND constraint_name = 'user_transfer_requests_submitted_batch_id_fkey'
  ) THEN
    ALTER TABLE public.user_transfer_requests
      ADD CONSTRAINT user_transfer_requests_submitted_batch_id_fkey
      FOREIGN KEY (submitted_batch_id)
      REFERENCES public.user_request_submissions(id)
      ON DELETE SET NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_user_transfer_requests_target_status
  ON public.user_transfer_requests(target_guest_id, status);

CREATE INDEX IF NOT EXISTS idx_user_transfer_requests_batch
  ON public.user_transfer_requests(submitted_batch_id);

CREATE INDEX IF NOT EXISTS idx_user_request_submissions_target
  ON public.user_request_submissions(target_guest_id, submitted_at DESC);

ALTER TABLE public.user_transfer_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_request_submissions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'user_transfer_requests' AND policyname = 'Allow all access to user_transfer_requests'
  ) THEN
    CREATE POLICY "Allow all access to user_transfer_requests"
      ON public.user_transfer_requests
      FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'user_request_submissions' AND policyname = 'Allow all access to user_request_submissions'
  ) THEN
    CREATE POLICY "Allow all access to user_request_submissions"
      ON public.user_request_submissions
      FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.submit_user_request_batch(
  p_target_guest_id TEXT,
  p_submitter_name TEXT,
  p_password TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_batch_id UUID;
  v_target_user public.users%ROWTYPE;
  v_request_count INTEGER;
BEGIN
  IF COALESCE(p_password, '') <> 'Anamul-984516' THEN
    RAISE EXCEPTION 'Invalid password';
  END IF;

  SELECT *
  INTO v_target_user
  FROM public.users
  WHERE guest_id = p_target_guest_id
  LIMIT 1;

  INSERT INTO public.user_request_submissions (
    target_user_id,
    target_guest_id,
    target_display_name,
    target_verified_count,
    submitted_to_admin_by,
    request_count
  )
  VALUES (
    v_target_user.id,
    p_target_guest_id,
    v_target_user.display_name,
    COALESCE(v_target_user.key_count, 0),
    COALESCE(NULLIF(p_submitter_name, ''), 'Unknown'),
    0
  )
  RETURNING id INTO v_batch_id;

  UPDATE public.user_transfer_requests
  SET
    status = 'submitted',
    submitted_batch_id = v_batch_id,
    submitted_at = now(),
    target_user_id = COALESCE(target_user_id, v_target_user.id)
  WHERE target_guest_id = p_target_guest_id
    AND status = 'pending';

  GET DIAGNOSTICS v_request_count = ROW_COUNT;

  UPDATE public.user_request_submissions
  SET request_count = v_request_count
  WHERE id = v_batch_id;

  INSERT INTO public.submitted_numbers (
    phone_number,
    verified_count,
    submitted_by,
    payment_number,
    payment_method
  )
  SELECT
    requester_guest_id,
    requester_verified_count,
    CONCAT('Request→', p_target_guest_id),
    requester_payment_number,
    requester_payment_method
  FROM public.user_transfer_requests
  WHERE submitted_batch_id = v_batch_id;

  RETURN v_batch_id;
END;
$$;