-- Add avatar_url column to users table
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url text;

-- Create storage bucket for avatars
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true) ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Allow public upload to avatars" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars');
CREATE POLICY "Allow public read avatars" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
CREATE POLICY "Allow public update avatars" ON storage.objects FOR UPDATE USING (bucket_id = 'avatars');
CREATE POLICY "Allow public delete avatars" ON storage.objects FOR DELETE USING (bucket_id = 'avatars');

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_id UUID UNIQUE;
INSERT INTO settings (key, value) VALUES ('videoUrl', 'https://youtube.com/shorts/xPEM62ZUV_0?feature=share') ON CONFLICT DO NOTHING;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email text;

-- User transfer request tables
CREATE TABLE IF NOT EXISTS public.user_request_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  target_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  target_guest_id TEXT NOT NULL,
  target_display_name TEXT,
  target_verified_count INTEGER NOT NULL DEFAULT 0,
  submitted_to_admin_by TEXT NOT NULL DEFAULT 'Unknown',
  request_count INTEGER NOT NULL DEFAULT 0,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitter_payment_number text,
  submitter_payment_method text,
  submitter_rate integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.user_transfer_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  requester_guest_id TEXT NOT NULL,
  requester_verified_count INTEGER NOT NULL DEFAULT 0,
  requester_payment_number TEXT NOT NULL,
  requester_payment_method TEXT,
  target_guest_id TEXT NOT NULL,
  target_user_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  submitted_batch_id UUID REFERENCES public.user_request_submissions(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_user_transfer_requests_target_status ON public.user_transfer_requests(target_guest_id, status);
CREATE INDEX IF NOT EXISTS idx_user_transfer_requests_batch ON public.user_transfer_requests(submitted_batch_id);
CREATE INDEX IF NOT EXISTS idx_user_request_submissions_target ON public.user_request_submissions(target_guest_id, submitted_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS user_transfer_requests_one_active_request_idx ON public.user_transfer_requests (requester_guest_id) WHERE status IN ('pending', 'submitted');

ALTER TABLE public.user_transfer_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_request_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read user_transfer_requests" ON public.user_transfer_requests FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Authenticated create own request" ON public.user_transfer_requests FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.auth_id = auth.uid() AND u.id = requester_user_id AND u.guest_id = requester_guest_id));
CREATE POLICY "Public read user_request_submissions" ON public.user_request_submissions FOR SELECT TO anon, authenticated USING (true);

-- Conversations table
CREATE TABLE public.conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  participant_1 integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  participant_2 integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  last_message text,
  last_message_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  UNIQUE(participant_1, participant_2)
);
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to conversations" ON public.conversations FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content text,
  message_type text NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'image', 'voice')),
  media_url text,
  is_read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to messages" ON public.messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_messages_conversation ON public.messages(conversation_id, created_at DESC);
CREATE INDEX idx_conversations_participant1 ON public.conversations(participant_1);
CREATE INDEX idx_conversations_participant2 ON public.conversations(participant_2);

ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

INSERT INTO storage.buckets (id, name, public) VALUES ('chat-media', 'chat-media', true) ON CONFLICT DO NOTHING;
CREATE POLICY "Anyone can upload chat media" ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'chat-media');
CREATE POLICY "Anyone can view chat media" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'chat-media');

INSERT INTO public.settings (key, value) VALUES ('paymentMode', 'off') ON CONFLICT DO NOTHING;

ALTER PUBLICATION supabase_realtime ADD TABLE public.settings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
ALTER PUBLICATION supabase_realtime ADD TABLE public.transactions;

-- Posts/Stories
CREATE TABLE public.posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content text,
  image_url text,
  video_url text,
  likes_count integer NOT NULL DEFAULT 0,
  comments_count integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to posts" ON public.posts FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.post_likes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(post_id, user_id)
);
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to post_likes" ON public.post_likes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.post_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  parent_comment_id uuid REFERENCES public.post_comments(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.post_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to post_comments" ON public.post_comments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.posts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.post_comments;

INSERT INTO storage.buckets (id, name, public) VALUES ('post-media', 'post-media', true) ON CONFLICT DO NOTHING;
CREATE POLICY "Allow all uploads to post-media" ON storage.objects FOR ALL TO anon, authenticated USING (bucket_id = 'post-media') WITH CHECK (bucket_id = 'post-media');

CREATE TABLE public.stories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  music_name text DEFAULT NULL,
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz DEFAULT (now() + interval '24 hours')
);
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to stories" ON public.stories FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.post_reactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reaction_type text NOT NULL DEFAULT 'like',
  created_at timestamptz DEFAULT now(),
  UNIQUE(post_id, user_id)
);
ALTER TABLE public.post_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to post_reactions" ON public.post_reactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.call_signals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  caller_id integer NOT NULL REFERENCES public.users(id),
  receiver_id integer NOT NULL REFERENCES public.users(id),
  signal_type text NOT NULL,
  signal_data jsonb,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.call_signals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to call_signals" ON public.call_signals FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.stories;
ALTER PUBLICATION supabase_realtime ADD TABLE public.post_reactions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.call_signals;

INSERT INTO storage.buckets (id, name, public) VALUES ('stories', 'stories', true) ON CONFLICT (id) DO NOTHING;
CREATE POLICY "Allow public read stories" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'stories');
CREATE POLICY "Allow upload stories" ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'stories');

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS online_at timestamp with time zone DEFAULT NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS cover_url text DEFAULT NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_reels_seen_at timestamptz;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_verified_badge boolean NOT NULL DEFAULT false;

CREATE TABLE public.friend_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id integer NOT NULL,
  receiver_id integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(sender_id, receiver_id)
);
ALTER TABLE public.friend_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to friend_requests" ON public.friend_requests FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.comment_likes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  comment_id uuid NOT NULL REFERENCES public.post_comments(id) ON DELETE CASCADE,
  user_id integer NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to comment_likes" ON public.comment_likes FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE UNIQUE INDEX IF NOT EXISTS comment_likes_unique ON public.comment_likes(comment_id, user_id);

CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id integer NOT NULL,
  from_user_id integer,
  type text NOT NULL DEFAULT 'mention',
  reference_id text,
  content text,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to notifications" ON public.notifications FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.message_hidden (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (message_id, user_id)
);
ALTER TABLE public.message_hidden ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to message_hidden" ON public.message_hidden FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.channel_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscriber_user_id integer NOT NULL,
  channel_user_id integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT channel_subscriptions_unique UNIQUE (subscriber_user_id, channel_user_id),
  CONSTRAINT channel_subscriptions_no_self CHECK (subscriber_user_id <> channel_user_id)
);
ALTER TABLE public.channel_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to channel_subscriptions" ON public.channel_subscriptions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.story_views (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id uuid NOT NULL REFERENCES public.stories(id) ON DELETE CASCADE,
  viewer_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  viewed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(story_id, viewer_user_id)
);
ALTER TABLE public.story_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to story_views" ON public.story_views FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
ALTER PUBLICATION supabase_realtime ADD TABLE public.story_views;

CREATE TABLE IF NOT EXISTS public.story_reactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id uuid NOT NULL REFERENCES public.stories(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reaction_type text NOT NULL DEFAULT 'love',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(story_id, user_id, reaction_type)
);
ALTER TABLE public.story_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to story_reactions" ON public.story_reactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.tiktok_videos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  video_url text NOT NULL,
  video_id text NOT NULL,
  caption text,
  added_by text NOT NULL DEFAULT 'admin',
  category text NOT NULL DEFAULT 'mixed',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.tiktok_videos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to tiktok_videos" ON public.tiktok_videos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.user_transfer_requests;